In [1]:
import numpy as np

In [3]:
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
print(a)
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [15]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
b = a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [17]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [18]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [25]:
y = np.empty([3,2], dtype = int)
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
y = np.zeros(5)
print(y)

[0. 0. 0. 0. 0.]


In [27]:
y = np.zeros((5,), dtype = np.int)
print(y)

[0 0 0 0 0]


In [30]:
bz = np.zeros((2,2), dtype=[('x','f'), ('y', 'i4')])
print(z)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [31]:
x=[1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [32]:
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)


[(1, 2, 3) (4, 5)]


In [33]:
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [34]:
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [35]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [36]:
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)

[10. 12. 14. 16. 18.]


In [37]:
a = np.linspace(10, 20,  5, endpoint =  True)  
print(a)

[10.  12.5 15.  17.5 20. ]


In [38]:
a =np.linspace(1,10,10,retstep= True)
 
print(a)
# 拓展例子
b =np.linspace(1,10,10).reshape([10,1])
print(b)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [39]:
# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10)  
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [40]:
a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [43]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
print(a)

[2 4 6]
[0 1 2 3 4 5 6 7 8 9]


In [44]:
print(a[2])

2
